using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
using DersDagitim.Application;
using DersDagitim.Domain;

namespace DersDagitim.Wpf;
public partial class DataManagementWindow : Window
{
    public DataManagementWindow() { InitializeComponent(); var actions = (StackPanel)((Grid)Content).Children[3]; var ascButton = new Button { Content = "Mevcut ASC Programı", Padding = new Thickness(12, 7, 12, 7), Margin = new Thickness(0, 0, 8, 0) }; ascButton.Click += (_, _) => new AscScheduleWindow { Owner = this }.ShowDialog(); actions.Children.Add(ascButton); Loaded += async (_, _) => await LoadAsync(); }
    private async Task LoadAsync() { var r = App.Dashboard.Repository; ClassesGrid.ItemsSource = (await r.GetClassesAsync()).Select(x => new ClassRow(x)).ToList(); TeachersGrid.ItemsSource = (await r.GetTeachersAsync()).ToList(); CoursesGrid.ItemsSource = (await r.GetCoursesAsync()).Select(x => new CourseRow(x)).ToList(); ResourcesGrid.ItemsSource = (await r.GetResourcesAsync()).ToList(); }
    private string Kind => EntityTabs.SelectedIndex switch { 0 => "class", 1 => "teacher", 2 => "course", _ => "resource" };
    private object? Selected => EntityTabs.SelectedIndex switch { 0 => ClassesGrid.SelectedItem is ClassRow x ? x.Source : null, 1 => TeachersGrid.SelectedItem, 2 => CoursesGrid.SelectedItem is CourseRow x ? x.Source : null, _ => ResourcesGrid.SelectedItem };
    private async void New_Click(object sender, RoutedEventArgs e) { var dialog = new EntityEditorWindow(Kind) { Owner = this }; if (dialog.ShowDialog() != true) return; await SaveAsync(dialog.Value!); }
    private async void Edit_Click(object sender, RoutedEventArgs e) { if (Selected is null) { MessageBox.Show("Önce bir kayıt seçin.", "Düzenleme", MessageBoxButton.OK, MessageBoxImage.Information); return; } var dialog = new EntityEditorWindow(Kind, Selected) { Owner = this }; if (dialog.ShowDialog() != true) return; await SaveAsync(dialog.Value!); }
    private async void Delete_Click(object sender, RoutedEventArgs e) { if (Selected is null) { MessageBox.Show("Önce bir kayıt seçin.", "Silme", MessageBoxButton.OK, MessageBoxImage.Information); return; } if (MessageBox.Show("Seçili kayıt silinsin mi? Bu işlem geri alınamaz.", "Silme onayı", MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; var id = Selected switch { Teacher x => x.Id, SchoolClass x => x.Id, Course x => x.Id, Resource x => x.Id, _ => Guid.Empty }; var table = Kind switch { "class" => "SchoolClasses", "teacher" => "Teachers", "course" => "Courses", _ => "Resources" }; await App.Dashboard.Repository.DeleteAsync(table, id); await LoadAsync(); }
    private async Task SaveAsync(object value) { var r = App.Dashboard.Repository; switch (value) { case Teacher x: await r.SaveTeacherAsync(x); break; case SchoolClass x: await r.SaveClassAsync(x); break; case Course x: await r.SaveCourseAsync(x); break; case Resource x: await r.SaveResourceAsync(x); break; } await LoadAsync(); }
    private void Availability_Click(object sender, RoutedEventArgs e) => new TeacherAvailabilityWindow { Owner = this }.ShowDialog();
    private void TeacherReport_Click(object sender, RoutedEventArgs e) => new TeacherReportWindow { Owner = this }.ShowDialog();
    private void Transition_Click(object sender, RoutedEventArgs e) => MessageBox.Show("Program geçişi; kaynak/hedef program, geçiş sınıfı-yılı, müfredat sürümü, uygunluk kuralı ve onay referansıyla modellenmiştir. Koşullar sabit kodlanmaz.", "Program geçiş kuralları", MessageBoxButton.OK, MessageBoxImage.Information);
    private void WebPreview_Click(object sender, RoutedEventArgs e) => new TeacherWebPreviewWindow { Owner = this }.ShowDialog();
    private async void WebImport_Click(object sender, RoutedEventArgs e) { if (MessageBox.Show("Okul web listesindeki öğretmenler içeri aktarılsın mı? Webde olmayan mevcut kayıtlar silinmeyecek; mevcut yük, uygunluk ve kilit alanları korunacak.", "Web listesini aktar", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes) return; await App.Dashboard.Repository.ImportTeachersAsync(TeacherWebDirectory.Teachers); await LoadAsync(); MessageBox.Show("Öğretmen listesi içeri aktarıldı. Aynı kısa kodu kullanan kişiler adlarına göre ayrı tutuldu; kodlar düzenlenebilir.", "Aktarım tamamlandı", MessageBoxButton.OK, MessageBoxImage.Information); }
    private void AscImport_Click(object sender, RoutedEventArgs e) { var d = new OpenFileDialog { Filter = "ASC XML dosyası|*.xml|Tüm dosyalar|*.*" }; if (d.ShowDialog() != true) return; try { var p = AscXmlParser.Parse(d.FileName); var summary = $"ASC XML önizlemesi\n\nDönem: {p.Periods}\nAralar: {p.Breaks}\nDersler: {p.Subjects}\nÖğretmenler: {p.Teachers}\nOdalar: {p.Rooms}\nSınıflar: {p.Classes}\nGruplar: {p.Groups}\nDers talepleri: {p.Lessons}\nKartlar/mevcut yerleşimler: {p.Cards}\n\nUyarı: {p.Warnings.Count}\n\nGerçek SQLite aktarımı yapılsın mı?"; if (MessageBox.Show(summary, "ASC XML önizleme ve onay", MessageBoxButton.YesNo, MessageBoxImage.Information) != MessageBoxResult.Yes) return; ImportAscAsync(p); } catch (Exception ex) { MessageBox.Show($"ASC XML okunamadı: {ex.Message}", "İçe aktarma hatası", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private async void ImportAscAsync(AscXmlPreview p) { try { var xmlTeachers = AscXmlCoreMapping.Teachers(p); await App.Dashboard.Repository.ImportAscXmlAsync(p); await App.Dashboard.Repository.CleanTeachersForAscAsync(xmlTeachers); await LoadAsync(); var teachers = (await App.Dashboard.Repository.GetTeachersAsync()).ToList(); var sourceCount = teachers.Count(x => x.SourceLabel == "ASC XML"); var outsideCount = teachers.Count(x => x.StaffStatus == "Dışarıdan ders veren"); MessageBox.Show($"ASC XML kurum verisi aktarıldı ve öğretmen listesi temizlendi.\n\nToplam öğretmen: {teachers.Count}\nXML kaynağı: {sourceCount}\nDışarıdan ders veren: {outsideCount}", "ASC XML aktarımı tamamlandı", MessageBoxButton.OK, MessageBoxImage.Information); } catch (Exception ex) { MessageBox.Show($"Aktarım geri alındı: {ex.Message}", "ASC XML aktarım hatası", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private async void AscExport_Click(object sender, RoutedEventArgs e) { var d = new SaveFileDialog { Filter = "ASC XML dosyası|*.xml", FileName = "ders-dagitim.asc.xml" }; if (d.ShowDialog() != true) return; try { await App.Dashboard.Repository.ExportAscXmlAsync(d.FileName); MessageBox.Show("ASC uyumlu XML dışa aktarıldı. Uygulamaya özel alanlar appmetadata uyarısıyla ayrıştırılmıştır.", "ASC XML dışa aktarımı", MessageBoxButton.OK, MessageBoxImage.Information); } catch (Exception ex) { MessageBox.Show($"Dışa aktarma başarısız: {ex.Message}", "ASC XML hatası", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private sealed class ClassRow(SchoolClass source) { public SchoolClass Source => source; public string Name => source.Name; public string? Department => source.Department; public string ProgramTypeText => source.ProgramType == SchoolProgramType.AnadoluTeknikProgrami ? "Anadolu Teknik Programı" : "Anadolu Meslek Programı"; public bool IsDemo => source.IsDemo; }
    private sealed class CourseRow(Course source) { 
        public Course Source => source; 
        public string Name => source.Name; 
        public string? Abbreviation => source.Abbreviation; 
        public int WeeklyHours => source.WeeklyHours; 
        public string BlockOptionsText => string.Join(", ", source.BlockOptions); 
        public string SourceText => $"{source.SourceLabel ?? "Kaynak belirtilmedi"} / {source.SourceVersion ?? "sürüm yok"}";
        public string TypeText => source.Type switch { CourseType.Zorunlu => "Zorunlu", CourseType.Seçmeli => "Seçmeli", CourseType.Kurs => "Kurs", CourseType.DYK => "DYK", _ => "Bilinmiyor" };
        public string ElectiveText => source.IsElective ? "✓ Seçmeli" : "";
    }
}
